# -*- coding: utf-8 -*-
"""dashboard_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ymH5Fr0ka0tLsiGRZ-MonkJszFstspjZ
"""




import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Sales Forecast Dashboard", layout="wide")

df = pd.read_csv("sales_predictions.csv")

st.title("📊 Sales Forecast Dashboard")

# Line Chart
fig = px.line(df, x="Date", y="Forecasted_Sales", title="📈 Forecasted Sales Over Time")
st.plotly_chart(fig, use_container_width=True)

# Show raw data
with st.expander("Show Forecast Table"):
    st.dataframe(df)

